- name: Ensure only ports 22 and 443 are open on webserver
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ ssh_port }}"
    - "{{ https_port }}"

- name: Enable ufw
  ufw:
    state: enabled
